### ISSUE TITLE
[minor] cannot see the preview text in font configuration

### ISSUE THREAD

**Issue by gayanper** [AObuchow/Eclipse-Modern-Dark-Theme#142] opened 2021-06-15 14:14 UTC
![image](https://user-images.githubusercontent.com/7471994/122068477-b9ed8f00-cdf4-11eb-8182-5b7ceddc0403.png)

**Comment by AObuchow** [comment] 2021-06-16 19:54
Yes this is an unfortunate bug that might only be fixable upstream. Ideally, the text preview color should be light or dark depending on the background color of the theme.

 It's also a duplicate of https://github.com/AObuchow/Eclipse-Spectrum-Theme/issues/57 so I'm closing it as a duplicate.

**Closed as completed by AObuchow** 2021-06-16 19:54 UTC
