### ISSUE TITLE
Javadoc is hard to Read

### ISSUE THREAD

**Issue by DKLEEE** [AObuchow/Eclipse-Modern-Dark-Theme#71] opened 2020-06-22 10:11 UTC
Hi,
the Javadoc View, and Tooltip/Hover is very hard to read.
For me it is Black font on Black background. 
![grafik](https://user-images.githubusercontent.com/16030367/85275617-de808680-b480-11ea-938a-fbde668cb302.png)

There already has been an issue where it was to light.
https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/issues/13

Windows
Eclipse 2020-06
Plugin version 1.0.7.202006190441

**Comment by AObuchow** [comment] 2020-06-22 14:41
Thanks for reporting @DKLEEE, I think I have an idea on how to fix this. Will keep you updated.

**Comment by AObuchow** [comment] 2020-06-22 15:05
@DKLEEE can you update and confirm the issue is now fixed?

**Closed** 2020-06-22 15:05 UTC
Labels: bug

**Comment by AObuchow** [comment] 2020-06-22 15:13
Also let me know if the issue also persists for Tooltip/Hover :)

**Comment by DKLEEE** [comment] 2020-06-24 08:23
Looks good now, thanks :)

![grafik](https://user-images.githubusercontent.com/16030367/85521526-a86c0f80-b604-11ea-8143-05571041ea36.png)

**Comment by AObuchow** [comment] 2020-06-24 10:39
@DKLEEE awesome thanks! You wouldn’t happen to know if the java doc scroll bars on Windows are also light on the platform dark theme like in the screenshot you sent?

**Comment by DKLEEE** [comment] 2020-06-24 11:14
I also noticed that.
Yes, the default Dark theme has the same Problem, so i wouldn't bother you here ;)
