### ISSUE TITLE
Variables view is hard to use

### ISSUE THREAD

**Issue by PyvesB** [AObuchow/Eclipse-Modern-Dark-Theme#63] opened 2020-06-18 14:17 UTC
Hello!

Today was a debugging session with a colleague! We noticed that the _Variables_ view suffers from a few problems:
* the yellow background makes variables very hard to read. I believe this is the "Changed value background color".
* the area around the expression drop-down is white. Note that this is also the case for the _Expressions_ view.

<img width="1060" alt="Screenshot 2020-06-18 at 15 52 44" src="https://user-images.githubusercontent.com/10694593/85028983-13889280-b17c-11ea-95d7-89cd389729c1.png">

Apart from that, the rest of the debugging session went fine, though I don't think I'll convince my colleague to move away from NetBeans today. 😄

**Comment by AObuchow** [comment] 2020-06-18 15:39
Thanks for reporting this @PyvesB ! This is a bug usability issue and needs to be fixed before the marketplace release.

The yellow must have been left in from months ago when I first started making this theme and was doing a lot of testing, as this existed in the first version of the theme.

Will get this fixed soon.

**Comment by AObuchow** [comment] 2020-06-18 16:40
@PyvesB I quickly tried to reproduced and was unable. Are you using the latest build of Modern Dark?

The new update site (in the README) is:
`https://raw.githubusercontent.com/AObuchow/Eclipse-Modern-Dark-Theme/updatesite/updatesite/`

**Comment by ingomohr** [comment] 2020-06-18 20:54
<img width="505" alt="Screenshot 2020-06-18 at 22 53 55" src="https://user-images.githubusercontent.com/2838592/85070737-9f1f1500-b1b6-11ea-968f-eadbd46a9caf.png">
This is what the Variables view looks on MacOS (Catalina, Eclipse 2020-06)

**Comment by AObuchow** [comment] 2020-06-19 04:42
The fix I submitted might be invalid. @PyvesB & @ingomohr please update to the latest build and validate the fix.

**Comment by PyvesB** [comment] 2020-06-19 07:19
Problem number 2 is fixed, i.e. the white area.

However, the yellow problem is still present on my machine with the latest version. Are you sure you've triggered the debug value changed functionality? Try with the following snippet:
````
import java.util.Random;

public class Main {

    public static void main(String[] args) {
        printHello();
        printHello();
    }

    private static void printHello() {
        int j = new Random().nextInt();
        System.out.println("hello");
    }
}
````

You must put the breakpoint on line `System.out.println("hello");`, no other line would reproduce the behaviour.

**Comment by AObuchow** [comment] 2020-06-19 10:09
Thanks for the detailed report on reproducing @PyvesB, that helps a lot. Will look into it.

@ingomohr or @PyvesB, would either of you mind posting a screenshot of the variable view (when you have a moment)? It seemed less affected by my last change on GTK than both your systems. I want to verify the colour is correct/exact :)

**Comment by PyvesB** [comment] 2020-06-19 10:32
<img width="1070" alt="Screenshot 2020-06-19 at 12 32 09" src="https://user-images.githubusercontent.com/10694593/85123671-f3fb7380-b228-11ea-8e8c-69b9b948d984.png">

**Comment by ingomohr** [comment] 2020-06-19 10:38
<img width="452" alt="Screenshot 2020-06-19 at 12 37 21" src="https://user-images.githubusercontent.com/2838592/85124114-a9c6c200-b229-11ea-8612-2ebf387b573e.png">

Build. 1.0.7.202006190441

**Comment by AObuchow** [comment] 2020-06-19 10:46
@PyvesB & @ingomohr thank you both that really helps. It's interesting to see the differences between both your screenshots too :P

**Comment by AObuchow** [comment] 2020-06-19 10:51
Some observations: 
- the color codes in the area that used to be white before the previous patch don't match up with the last change I made.
- that color is different between both of your systems (#242427 vs #252529)

**Comment by PyvesB** [comment] 2020-06-19 10:54
@ingomohr did you try pressing "Continue"? It's only when the breakpoint is hit for a second time that the "Changed value background color" is set.

**Comment by AObuchow** [comment] 2020-06-19 10:59
How it looks on Linux using a light GTK theme.
![image](https://user-images.githubusercontent.com/10300119/85125658-0316fd00-b1fa-11ea-8c2c-6f250845723e.png)

Instead of yellow, it's `#914d6f` or `rgb(145, 77, 111)`

This is in accordance with the preference I set [here](https://github.com/AObuchow/Eclipse-Modern-Dark-Theme/blob/master/com.aobuchow.themes.moderndark/css/preference_styles.css#L100):
`'org.eclipse.debug.ui.PREF_CHANGED_VALUE_BACKGROUND=145,77,111'`

**Comment by ingomohr** [comment] 2020-06-19 11:03
> @ingomohr did you try pressing "Continue"? It's only when the breakpoint is hit for a second time that the "Changed value background color" is set.

![variable-view-debug](https://user-images.githubusercontent.com/2838592/85126099-142d3180-b22d-11ea-9fe4-6f25e502d245.gif)

Not - but now I did. ;) - (see gif)

**Comment by AObuchow** [comment] 2020-06-19 11:07
@ingomohr's changed color seems to be correct (although I'm going to change the color to something else...)

@PyvesB maybe it's a workspace preference that's overriding the CSS preference? Might be worth trying to make a new test-workspace, enable Modern Dark theme and try reproducing.

**Comment by AObuchow** [comment] 2020-06-19 11:10
Run/Debug seems to be the associated preference page:
![image](https://user-images.githubusercontent.com/10300119/85126704-ff847580-b1fb-11ea-83e4-a9502fcd0dba.png)

**Comment by ingomohr** [comment] 2020-06-19 11:12
> Run/Debug seems to be the associated preference page:
> ![image](https://user-images.githubusercontent.com/10300119/85126704-ff847580-b1fb-11ea-83e4-a9502fcd0dba.png)

The colors look the same on my machine.

**Comment by PyvesB** [comment] 2020-06-19 12:06
Hmmm... Something is definitely not lining up for me. Here's what my preferences page looks like for debug options:
<img width="612" alt="Screenshot 2020-06-19 at 13 02 24" src="https://user-images.githubusercontent.com/10694593/85130792-e13b6b80-b235-11ea-8236-65c4b503d8e7.png">

I did try with a new workspace and Oomph disabled, to no avail. "Restore Defaults" does nothing either.

**Comment by PyvesB** [comment] 2020-06-19 12:12
After some further analysis, there is some sort of startup task that puts the following entry in newly created workspaces:
`./.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.debug.ui.prefs:8:org.eclipse.debug.ui.PREF_CHANGED_VALUE_BACKGROUND=255,255,0`

Not sure where that comes from yet.

**Comment by AObuchow** [comment] 2020-06-19 12:14
@PyvesB if you're comfortable with it & allowed, feel free to show a screenshot of your installed plugins list (Help > About Eclipse SDK... > Installation details). I'll try to help find the cause.

**Comment by PyvesB** [comment] 2020-06-19 13:34
It does seem that Oomph is doing stuff at startup even though the preference recorder is disabled. I saw this in the startup logs:
```
Scope Type | User
-- | --
Disabled | false
Predecessors | /instance/org.eclipse.debug.ui/org.eclipse.debug.ui.outColor = 0,0,0 (User - User Preferences - org.eclipse.debug.ui)
Key | /instance/org.eclipse.debug.ui/org.eclipse.debug.ui.PREF_CHANGED_VALUE_BACKGROUND
Value | 255,255,0
Model Class | org.eclipse.oomph.setup.PreferenceTask
```

**Comment by PyvesB** [comment] 2020-06-19 13:45
I've disabled this specific entry in Oomph, it now gives me the correct colours on new workspaces. 👍 

I'm still confused as to why I was not able to easily switch to the value provided by Modern Dark Theme. If I'm not mistaken, resetting default entries in "Colors and Fonts" switches to the values provided by CSS, but this is not the case for the Run/Debug preference window.

**Comment by AObuchow** [comment] 2020-06-19 14:26
> I've disabled this specific entry in Oomph, it now gives me the correct colours on new workspaces. +1

Glad to hear you fixed it :) 

> 
> I'm still confused as to why I was not able to easily switch to the value provided by Modern Dark Theme. If I'm not mistaken, resetting default entries in "Colors and Fonts" switches to the values provided by CSS, but this is not the case for the Run/Debug preference window.

Might be worth making an upstream bug in platform.debug.ui? If you do so, CC me in it :)

I'm going to close this for now as I'm undecided about what the new debug colors should be right now. 

If anyone finds the debug variable view colors still unpleasant to use, please reopen the bug and let me know :)

**Closed by AObuchow** 2020-06-19 14:26 UTC
Labels: bug
